In [19]:
import pandas as pd
import numpy as np

###  Reading Datasets

In [20]:
companies  = pd.read_csv("data/companies.csv",encoding= 'palmos')

In [21]:
rounds2 = pd.read_csv("data/rounds2.csv",encoding= 'palmos')

### Understanding the datasets

In [22]:
companies.head(30)

,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at
0,/Organization/-Fame,#fame,http://livfame.com,Media,operating,IND,16,Mumbai,Mumbai,NaN
1,/Organization/-Qounter,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City,04-09-2014
2,/Organization/-The-One-Of-Them-Inc-,"(THE) ONE of THEM,Inc.",http://oneofthem.jp,Apps|Games|Mobile,operating,NaN,NaN,NaN,NaN,NaN
3,/Organization/0-6-Com,0-6.com,http://www.0-6.com,Curated Web,operating,CHN,22,Beijing,Beijing,01-01-2007
4,/Organization/004-Technologies,004 Technologies,http://004gmbh.de/en/004-interact,Software,operating,USA,IL,"Springfield, Illinois",Champaign,01-01-2010
5,/Organization/01Games-Technology,01Games Technology,http://www.01games.hk/,Games,operating,HKG,NaN,Hong Kong,Hong Kong,NaN
6,/Organization/0Ndine-Biomedical-Inc,Ondine Biomedical Inc.,http://ondinebio.com,Biotechnology,operating,CAN,BC,Vancouver,Vancouver,01-01-1997
7,/Organization/0Xdata,H2O.ai,http://h2o.ai/,Analytics,operating,USA,CA,SF Bay Area,Mountain View,01-01-2011
8,/Organization/1,One Inc.,http://whatis1.com,Mobile,operating,USA,CA,SF Bay Area,San Francisco,01-08-2011
9,/Organization/1-2-3-Listo,"1,2,3 Listo",http://www.123listo.com,E-Commerce,operating,CHL,12,Santiago,Las Condes,01-01-2012
10,/Organization/1-4-All,1-4 All,NaN,Entertainment|Games|Software,operating,USA,NC,NC - Other,Connellys Springs,NaN
11,/Organization/1-618-Technology,1.618 Technology,http://www.Homeandcondogallery.com,Networking|Real Estate|Web Hosting,operating,USA,FL,Orlando,Orlando,07-12-2013
12,/Organization/1-800-Dentist,1-800-DENTIST,http://www.1800dentist.com,Health and Wellness,operating,USA,CA,Los Angeles,Los Angeles,01-01-1986
13,/Organization/1-800-Doctors,1-800-DOCTORS,http://1800doctors.com,Health and Wellness,operating,USA,NJ,Newark,Iselin,01-01-1984
14,/Organization/1-800-Publicrelations-Inc-,"1-800-PublicRelations, Inc.",http://www.1800publicrelations.com,Internet Marketing|Media|Public Relations,operating,USA,NY,New York City,New York,24-10-2013
15,/Organization/1-Mainstream,1 Mainstream,http://www.1mainstream.com,Apps|Cable|Distribution|Software,acquired,USA,CA,SF Bay Area,Cupertino,01-03-2012
16,/Organization/1-Of-99,1 of 99,NaN,Entertainment|Games,operating,USA,CA,SF Bay Area,Mountain View,01-12-2014
17,/Organization/10-20-Media,10-20 Media,http://www.10-20media.com,E-Commerce,operating,USA,MD,Baltimore,Woodbine,01-01-2001
18,/Organization/10-Minutes-With,10 Minutes With,http://10minuteswith.com,Education,operating,GBR,H9,London,London,01-01-2013
19,/Organization/1000-Corks,1000 Corks,http://1000corks.com,Search,operating,USA,OR,"Portland, Oregon",Lake Oswego,01-01-2008
20,/Organization/1000-Markets,1000 Markets,http://www.1000markets.com,Art|E-Commerce|Marketplaces,acquired,USA,WA,Seattle,Seattle,01-01-2009
21,/Organization/1000Chi,Beijing 1000CHI Software Technology,http://www.1000chi.com/,Mobile,operating,NaN,NaN,NaN,NaN,01-01-2008
22,/Organization/1000Lookz,1000Lookz,http://1000lookz.com,Beauty,operating,IND,25,Chennai,Chennai,01-01-2008
23,/Organization/1000Memories,1000memories,http://1000memories.com,Curated Web,acquired,USA,CA,SF Bay Area,San Francisco,01-07-2010
24,/Organization/1000Museums-Com,1000museums.com,http://www.1000museums.com,Curated Web,operating,USA,MA,MA - Other,Lenox,01-01-2008
25,/Organization/1001-Menus,ZenChef,http://zenchef.com/en/,Local Businesses|Restaurants,operating,FRA,A8,Paris,Paris,20-11-2010
26,/Organization/1001Pharmacies-Com,1001pharmacies.com,http://www.1001pharmacies.com/,Cosmetics|Marketplaces,operating,FRA,A9,Montpellier,Montpellier,01-01-2012
27,/Organization/1006-Tv,1006.tv,http://www.1006.tv/,Games|Media,operating,CHN,22,Beijing,Beijing,01-01-2009
28,/Organization/100Du-Tv,100du.tv,http://www.100du.com,Hospitality,operating,CHN,23,Shanghai,Shanghai,NaN
29,/Organization/100E-Com,100e.com,http://www.100e.com,Education,operating,CHN,22,Beijing,Beijing,NaN

In [23]:
rounds2.head(30)

,company_permalink,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd
0,/organization/-fame,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,B,05-01-2015,10000000.0
1,/ORGANIZATION/-QOUNTER,/funding-round/22dacff496eb7acb2b901dec1dfe5633,venture,A,14-10-2014,NaN
2,/organization/-qounter,/funding-round/b44fbb94153f6cdef13083530bb48030,seed,NaN,01-03-2014,700000.0
3,/ORGANIZATION/-THE-ONE-OF-THEM-INC-,/funding-round/650b8f704416801069bb178a1418776b,venture,B,30-01-2014,3406878.0
4,/organization/0-6-com,/funding-round/5727accaeaa57461bd22a9bdd945382d,venture,A,19-03-2008,2000000.0
5,/ORGANIZATION/004-TECHNOLOGIES,/funding-round/1278dd4e6a37fa4b7d7e06c21b3c1830,venture,NaN,24-07-2014,NaN
6,/organization/01games-technology,/funding-round/7d53696f2b4f607a2f2a8cbb83d01839,undisclosed,NaN,01-07-2014,41250.0
7,/ORGANIZATION/0NDINE-BIOMEDICAL-INC,/funding-round/2b9d3ac293d5cdccbecff5c8cb0f327d,seed,NaN,11-09-2009,43360.0
8,/organization/0ndine-biomedical-inc,/funding-round/954b9499724b946ad8c396a57a5f3b72,venture,NaN,21-12-2009,719491.0
9,/ORGANIZATION/0XDATA,/funding-round/383a9bd2c04f7038bb543ccef5ba3eae,seed,NaN,22-05-2013,3000000.0
10,/organization/0xdata,/funding-round/3bb2ee4a2d89251a10aaa735b1180e44,venture,B,09-11-2015,20000000.0
11,/ORGANIZATION/0XDATA,/funding-round/ae2a174c06517c2394aed45006322a7e,venture,NaN,03-01-2013,1700000.0
12,/organization/0xdata,/funding-round/e1cfcbe1bdf4c70277c5f29a3482f24e,venture,A,19-07-2014,8900000.0
13,/ORGANIZATION/1,/funding-round/03b975068632eba5bfdb937ec8c07a68,seed,NaN,05-02-2014,150000.0
14,/organization/1,/funding-round/5de6d8828aef7d925d97918d15727670,undisclosed,NaN,05-02-2013,NaN
15,/ORGANIZATION/1,/funding-round/e82464f22241715dd1a6c77241055ed1,seed,NaN,20-07-2011,1000050.0
16,/organization/1-2-3-listo,/funding-round/6de4609e894495105bc791ed64361288,seed,NaN,18-02-2013,40000.0
17,/ORGANIZATION/1-4-ALL,/funding-round/e97a192e13ea0ee3c4f71136b4f3ec16,equity_crowdfunding,NaN,21-04-2013,NaN
18,/organization/1-618-technology,/funding-round/83b8f4c7d37ecef5e001a5e953bf461a,equity_crowdfunding,NaN,22-01-2014,NaN
19,/ORGANIZATION/1-800-DENTIST,/funding-round/5274aacc211163fc7c86539ce94bbacc,undisclosed,NaN,19-08-2010,NaN
20,/organization/1-800-doctors,/funding-round/9eb8c7790a0c200d79e75785d1c4aa12,convertible_note,NaN,02-03-2011,1750000.0
21,/ORGANIZATION/1-800-PUBLICRELATIONS-INC-,/funding-round/11c228f58831bc7ed337ef69ecc560c2,private_equity,NaN,01-02-2015,6000000.0
22,/organization/1-mainstream,/funding-round/b952cbaf401f310927430c97b68162ea,venture,NaN,17-03-2015,5000000.0
23,/ORGANIZATION/1-OF-99,/funding-round/b5c811f561cfb5701cd5b1762120bbc3,convertible_note,NaN,13-12-2014,100000.0
24,/organization/10-20-media,/funding-round/436874dc54b54460f99f44c06e50990a,debt_financing,NaN,11-01-2011,800000.0
25,/ORGANIZATION/10-20-MEDIA,/funding-round/8025ee9c11a586eac4a234ddec7beb30,debt_financing,NaN,18-06-2009,500000.0
26,/organization/10-20-media,/funding-round/a884bf8326b9fd59789c0f74a28dbc3b,debt_financing,NaN,28-12-2011,500000.0
27,/ORGANIZATION/10-20-MEDIA,/funding-round/d205f5416ce55e126beda3ed2bf2c2cd,debt_financing,NaN,30-03-2010,250000.0
28,/organization/10-minutes-with,/funding-round/0faccbbcc5818dc5326469f13f5a8ac8,venture,A,09-10-2014,4000000.0
29,/ORGANIZATION/10-MINUTES-WITH,/funding-round/f245a74b4c54610ae843e17bdf4d1113,seed,NaN,01-01-2013,400000.0

### Data Cleaning

In [24]:
#Removing the special characters in Permalink column.
companies["permalink"] = companies["permalink"].str.encode('ascii','ignore').str.decode('ascii').str.lower()

In [25]:
#Removing the special characters in name column.
companies["name"] = companies["name"].str.encode('ascii','ignore').str.decode('ascii').str.lower()

In [26]:
companies.head()

,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at
0,/organization/-fame,#fame,http://livfame.com,Media,operating,IND,16,Mumbai,Mumbai,NaN
1,/organization/-qounter,:qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City,04-09-2014
2,/organization/-the-one-of-them-inc-,"(the) one of them,inc.",http://oneofthem.jp,Apps|Games|Mobile,operating,NaN,NaN,NaN,NaN,NaN
3,/organization/0-6-com,0-6.com,http://www.0-6.com,Curated Web,operating,CHN,22,Beijing,Beijing,01-01-2007
4,/organization/004-technologies,004 technologies,http://004gmbh.de/en/004-interact,Software,operating,USA,IL,"Springfield, Illinois",Champaign,01-01-2010

In [27]:
#Removing the special characters in the permalink column
rounds2["company_permalink"]=rounds2["company_permalink"].str.encode('ascii','ignore').str.decode('ascii').str.lower()

In [28]:
#### Understanding the datasets

In [29]:
companies.isnull().sum()

permalink            0
name                 1
homepage_url      5058
category_list     3148
status               0
country_code      6958
state_code        8547
region            8030
city              8028
founded_at       15221
dtype: int64

In [30]:
rounds2.isnull().sum() ## unique companies in rounds2 dataframe

company_permalink              0
funding_round_permalink        0
funding_round_type             0
funding_round_code         83809
funded_at                      0
raised_amount_usd          19990
dtype: int64

In [31]:
#Unique comapnies in round2
rounds2["company_permalink"].nunique(dropna=True)

66368

In [32]:
#Unique companies in  companies.csv
companies["permalink"].nunique(dropna=True)

66368

In [33]:
#To check if company available in Companies dataframe is not avilable in rounds2 dataframe
companies.loc[~rounds2.company_permalink.isin(companies.permalink)]

Empty DataFrame
Columns: [permalink, name, homepage_url, category_list, status, country_code, state_code, region, city, founded_at]
Index: []

In [34]:
#Merge companies and rounds2 dataframes to a new dataframe named "master_frame"
master_frame=pd.merge(companies, rounds2, left_on='permalink', right_on='company_permalink', how='inner')

In [35]:
master_frame.shape

(114949, 16)